### ISSUE TITLE
moga-mobo の JIS2004 字形

### ISSUE THREAD

**Issue by aminophen** [zr-tex8r/PXchfon#3]
勘違いだったらすみません。

~~~~ tex
% 文字コードはUTF-8 (platex -kanji=utf8)
\documentclass[a6paper,papersize]{jsarticle}
\usepackage[deluxe]{otf}
\usepackage[moga-mobo,prefer2004jis]{pxchfon}
\begin{document}
\mcfamily
葛餅で蓬餅で、かつ煎餅！\par
\mgfamily
葛餅で蓬餅で、かつ煎餅！\par
\gtfamily
葛餅で蓬餅で、かつ煎餅！\par
\ebseries
葛餅で蓬餅で、かつ煎餅！\par
\bfseries
葛餅で蓬餅で、かつ煎餅！\par
\mcfamily
葛餅で蓬餅で、かつ煎餅！\par
\ltseries
葛餅で蓬餅で、かつ煎餅！
\end{document}
~~~~

これの結果が、noprefer2004jis のときと同じになってしまいます。

~~それから、JIS2000 字形のほうの mobo の TTC index が 3 になって~~ ← これは違ったので撤回。

**Comment by aminophen** [comment]
> 標準和文フォントのCMap を

だから、otf のは切り替わらないということですね。失礼しました。

**Comment by aminophen** [comment]
あっ、でも upLaTeX + otf のときの 2004 字形の mapping が不完全なようです。
~~~~ tex
\documentclass[a6paper,papersize,uplatex]{jsarticle}
\usepackage[deluxe,jis2004]{otf}
\usepackage[moga-mobo,prefer2004jis]{pxchfon}
~~~~
updmap で hiragino-pron を設定している環境ですが、moga-mobo 指定にもかかわらず
~~~~
dvipdfmx:warning: Could not locate a virtual/physical font for TFM "uphminln-h".
dvipdfmx:warning: >> This font is mapped to a physical font "HiraMinProN-W2.otf".
dvipdfmx:warning: >> Please check if kpathsea library can find this font: HiraMinProN-W2.otf
dvipdfmx:fatal: Cannot proceed without .vf or "physical" font for PDF output...
~~~~
が出てきました。確かに pxchfon の中で未設定になっているようです。

**Comment by aminophen** [comment]
hiragino-elcapitan 系は texjporg/jfontmaps@9af223b で HiraMin*-W2.otf から W3.ttc に変えているので、一応お知らせしておきます。

**Comment by zr-tex8r** [comment]
>   hiragino-elcapitan 系は texjporg/jfontmaps@9af223b で HiraMin*-W2.otf から W3.ttc に変えているので、一応お知らせしておきます。

これについては、マニュアル上で明記されていることなので、変えると「仕様変更」になってしまいます。
それを押してまで変える必要性もないと思うので、現状維持にしておきます。

（upTeXの`prefer2004jis`については、実は仕様をわざと曖昧にしていた。）

**Comment by aminophen** [comment]
了解しました。ありがとうございます。
