### ISSUE TITLE
! LaTeX Error: Unknown option `noto' for package `pxchfon'.

### ISSUE THREAD

**Issue by aminophen** [zr-tex8r/PXchfon#5]
noto オプションが動かず，標記のエラーが出ます。コードを見ると， `%` で行末と次の行頭がくっついて「notoipa-otf」という意図しないオプションができてしまっているような？

＃ ところで，otf/otc なフォントに対しても cid-ナントカ な tfm に対して `/AJ16` が付くのですね。問題は起きないのかもしれませんが，少し気になります。

**Comment by zr-tex8r** [comment]
> コードを見ると， % で行末と次の行頭がくっついて「notoipa-otf」という意図しないオプションができてしまっているような？

どうやら、「手元に十分にテストをしないままリリースする悪いTeX言語者」がどこかにいたようです。

**Comment by aminophen** [comment]
（仮に私だったとしたら、noto / sourcehan 系の 4 種類のうち一個しかテストしない気がする…）

~~ゴシックでエラー~~ ← 勘違いだったので削除

**Comment by aminophen** [comment]
> ゴシックでエラー

おっと、もう一度 zip を展開しなおしたら正常になりました。何か壊れたのかも… お騒がせしました。

以下は pxchfon の問題ではないのですが、PDF のフォント情報は OTC index 1〜3 の中韓フォントを使っても jp なのですね：

<img width="950" alt="notootc-test" src="https://user-images.githubusercontent.com/9957466/27636841-7aab900c-5c48-11e7-8e90-dd7dbd9cffab.png">

**Comment by zr-tex8r** [comment]
> ＃ ところで，otf/otc なフォントに対しても cid-ナントカ な tfm に対して /AJ16 が付くのですね。問題は起きないのかもしれませんが，少し気になります。

多分、当初の開発時に、そういうアレな「マップ行の例示」がネット上にあふれていた、のでしょうな。実際に /AJ16 の有無を適切に選ぶ（つまり指定のフォントがCFFグリフかTTFグリフかを判定する）のは絶望的に困難なので、「常に /AJ16 があるのも可とする」しか仕方がなかったのでしょう。

ダンプ出力のことを考えると、やっぱり何とかしたほうがよいですね……、でもやっぱり何とかするのは絶望的に困難だ（むむむ……）。

**Comment by aminophen** [comment]
> ダンプ出力のことを考えると、やっぱり何とかしたほうがよいですね

ダンプのことを考えないにしても、少なくとも「AI0 なときに \CID のマップを付けてしまう」のは良くない気がします。例えば

~~~~
\usepackage[noto-otc]{pxchfon}
~~~~

とすると、kanji-config-updmap 由来の「使える cid- マップ」が pxchfon 由来の「使えない cid- マップ」に上書きされてしまいます。「\CID だけヒラギノ」とかいう状態がいいのかどうかわかりませんが、化けるよりはマシという考えかたができると思っています。

<img width="978" alt="2017-06-28 21 31 05" src="https://user-images.githubusercontent.com/9957466/27637023-27a395d4-5c49-11e7-9649-37102f165639.png">

**Comment by aminophen** [comment]
とは言いながら、「ではどう実装すればいいのか」と言われると、うーん、ですよね…。

**Comment by zr-tex8r** [comment]
.TeXでフォントの種類を判別してナントカ、はどうしようもないので、結局「どういうユーザインタフェースにするか」という話になるような気がしますが、それはそれでまた難しい……。

**Comment by aminophen** [comment]
ユーザインタフェースは難しいですね… 問題は致命的ではないのでお時間のあるときで構わないです。

今気づきましたが、noto-otc において uprml-hq と upgbm-hq の OTC index が「2」つまり簡体中国語に割り当てられているのは、何か理由があるのでしょうか？

~~~~
{pdf:mapline uprml-hq unicode :2:NotoSerifCJK-Regular.ttc -l fwid}
{pdf:mapline upgbm-hq unicode :2:NotoSansCJK-Medium.ttc -l fwd}
~~~~

**Comment by zr-tex8r** [comment]
もちろん、本来は

    uprml-hq unicode :0:NotoSerifCJK-Regular.ttc -l fwid
    upgbm-hq unicode :0:NotoSansCJK-Medium.ttc -l fwid

としたいですけど、これだと上手くいかない、ですよね。

**Comment by aminophen** [comment]
試しに 0 に変えて簡単なものをコンパイルしてみましたが，違いを見いだせていないです。

~~~~ tex
\documentclass[uplatex]{jsarticle}
\begin{document}
TEST“おはよう、ありがとう”。\par % <= クオートが uprml-hq
TEST‘おはよう、ありがとう’。\par % <= クオートが uprml-hq
\end{document}
~~~~

**Comment by zr-tex8r** [comment]
アレレ、自分の手元ではコレにしかならないんだが。

![image-notosansfwid-11](https://user-images.githubusercontent.com/932984/27641503-0057e666-5c57-11e7-89aa-91c491e5aa7c.png)

**Comment by aminophen** [comment]
GitHub で zip ファイルは送れるのかな？ [notomaptest.zip](https://github.com/zr-tex8r/PXchfon/files/1108982/notomaptest.zip)

Mac 環境で手元の Adobe Acrobat Pro DC では正常です。

**Comment by aminophen** [comment]
私のは Mac でセルフビルドした最新の dvipdfmx だったので、同じ Mac バイナリでも TeX Live 2017 に入っているものに巻き戻して試してみると… 再現しました。dvipdfmx のバグだったのでしょうか？

**Comment by zr-tex8r** [comment]
* zipの中のnotomaptest.pdfをこちらのAdobe Acrobat Reader DCで見る→フツー
* zipの中のnotomaptest.texを改めてコンパイルしてAdobe Acrobat Reader DCで見る→アレ

dvipdfmxのバージョンが違うのかな？

**Comment by zr-tex8r** [comment]
こちらの環境は単純にテフライブ2017の最新です。

```text
C>dvipdfmx --version
This is dvipdfmx Version 20170318 by the DVIPDFMx project team,
modified for TeX Live,
an extended version of dvipdfm-0.13.2c developed by Mark A. Wicks.

Copyright (C) 2002-2017 the DVIPDFMx project team
Copyright (C) 2006-2017 SIL International.

This is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.
```

**Comment by aminophen** [comment]
なるほど。おそらく r44689 と r44691 でバグ修正されたのだと推測します。私のテストはこれより後のバイナリで試していました。

うーむ、今 ptex-fontmaps で noto-otc とかを追加する作業をしているのですが、マップは mkmap-**.lua で自動生成しているので、この例外処理をつけるのはかなり面倒orz

**Comment by zr-tex8r** [comment]
一般人はアレが起こる、ということですね……。

> うーむ、今 ptex-fontmaps で noto-otc とかを追加する作業をしているのですが

あと、ptex-fontmapsの方は「本当に中国語」の設定もあるので、日本語のところで変なことをやると、「本当に中国語」の方に悪影響が及ぶ（同じ理由で）、という問題があるでしょう。

**Comment by zr-tex8r** [comment]
> マップは mkmap-**.lua で自動生成しているので、この例外処理をつけるのはかなり面倒orz

マップはTeX言語 :scream:  で自動生成しているので、この例外処理をつけるのは実際にかなり面倒:sob:

**Comment by aminophen** [comment]
そうか、一つのフォントで一つの OpenType Layout しか付けられないバグなので、ptex-fontmaps では「変なことをやってはいけない」になるのですね…

**Comment by zr-tex8r** [comment]
実はこれは回避可能、だったりします。
「本当に中国語」の方は属性無しの指定なので、uprml-hqの方も

    uprml-hq unicode :2:NotoSerifCJK-Regular.ttc

コレにする以外の選択肢が無い、のですが、**実はコレで上手くいきます**。

**Comment by zr-tex8r** [comment]
```text
* tt_cmap.c: Fix a bug that different CMaps are not attached 
  to each instances of font using different OpenType layout features. 
  Fix a bug that ToUnicode support for substituted glyph was incomplete. 
```

直ってる！！

**Comment by aminophen** [comment]
おお、回避可能なのですね！ 弊害がないかどうかもう少し考えてから、この方法を使わせていただこうと思います。（この場合、TeX Live 2018 pretest に入ったら「普通の」方法に戻すつもりです；そうしないと、例えば Language-specific OTF を使っている人が「日本語だけ使いたいのに、クオートのためだけに SC の .otf もダウンロードしないといけない」ので。）

**Comment by aminophen** [comment]
texjporg/ptex-fontmaps の dpxquote ブランチ [14db981](https://github.com/texjporg/jfontmaps/commit/14db9815e70de17beee539749389b14a47799336) に回避策を入れてみました。いろいろありがとうございました。

なお、pxchfon の noto(-otc) では「丸ゴ」に「ゴシックEB」と同じ Black が使われていますが、被るとせっかくのウェイトが勿体ないので、ptex-fontmaps では「丸ゴ」に Medium を割り当ててみました。

**Comment by zr-tex8r** [comment]
> 被るとせっかくのウェイトが勿体ない

これは、「丸ゴに何を充てるかを自分では決めたくなかったので敢えて役に立たない状態にした」ということです。ptex-fontmapsでゴシックMediumに決めたのであれば、こちらもそれに追随したいと思います。

**Comment by aminophen** [comment]
v1.1a までに相当改善されているようなので，閉じます。いつもありがとうございます。
